### ISSUE TITLE
Possible error in dev-0/in.tsv

### ISSUE THREAD

**Issue by apohllo** [poleval/2021-question-answering#2]
According to the dataset description it should not contain references to "current" roles.
Yet in the 110 line of dev-0/in.tsv there is a question:
`Jak nazywa się prezydent Ukrainy?`

**Comment by maciej-ogrodniczuk** [comment]
Poprawiam na „Jak nazywa się wybrany w 2019 r. prezydent Ukrainy?”

**Comment by apohllo** [comment]
:+1:
