### ISSUE TITLE
Error in test-A/expected.tsv

### ISSUE THREAD

**Issue by apohllo** [poleval/2021-question-answering#3]
The line 815 includes the following entry:
`Bohaterem której powieści Witolda Gombrowicza jest profesor Pimko?`
which is a question, not an answer.

**Comment by maciej-ogrodniczuk** [comment]
Faktycznie, coś się skleiło. Dopisuję poprawną odpowiedź, a Pimko wylatuje.

**Comment by apohllo** [comment]
:+1:
